server:
  port: 8084

spring:
  application:
    name: gateway-ws
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employee/**


      
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka