server:
  port: 8000

spring:
  application:
    name: gateway-ws
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: REFERRAL-SERVICE
          uri: lb://REFERRAL-SERVICE
          predicates:
            - Path=/referral/**

      
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka